name: Push dist

on:
  push:
    branches:
      - main
      - master

jobs:
  push-dist:
    name: Push dist
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: NullVoxPopuli/action-setup-pnpm@v2.3.1
      - uses: kategengler/put-built-npm-package-contents-on-branch@v2.1.0
        with:
          branch: dist
          token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: ember-query-params-service
