name: CI

# Inspiration:
# https://github.com/alexdiliberto/ember-transformicons/blob/master/.github/workflows/ci.yml
on:
  pull_request:
  push:
    # filtering branches here prevents duplicate builds from pull_request and push
    branches:
      - master

env:
  CI: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: volta-cli/action@v1
    - name: Install
      run: yarn install
    - name: ESLint
      run: yarn lint:js
    - name: Templates
      run: yarn lint:hbs
    - name: Types
      run: yarn lint:types
    - uses: wagoid/commitlint-github-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}

  tests:
    name: Ember Compatability
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scenario:
        - "ember-3.13"
        - "ember-3.14"
        - "ember-3.16"
        - "ember-3.18"
        - "ember-release"
        - "ember-beta"
        - "ember-canary"
    steps:
    - uses: actions/checkout@v2
    - uses: volta-cli/action@v1
    - name: Install
      run: yarn install
    - name: Test with ${{ matrix.scenario }}
      run: yarn test:try-one ${{ matrix.scenario }}

  publish:
    name: Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: [tests]

    steps:
    - uses: actions/checkout@v2
    - uses: volta-cli/action@v1
    - run: yarn install
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: yarn semantic-release
