name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - main

env:
  CI: true

jobs:
  install_dependencies:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - uses: wyvox/action@v1

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [install_dependencies]
    steps:
      - uses: wyvox/action@v1
      - run: pnpm lint

  default_tests:
    name: Default Tests
    timeout-minutes: 5
    runs-on: ubuntu-latest
    needs: [install_dependencies]
    steps:
      - uses: wyvox/action@v1
      - run: pnpm test:ember

  floating_tests:
    name: Floating Deps Test
    timeout-minutes: 5
    runs-on: ubuntu-latest
    needs: [default_tests]
    steps:
      - uses: wyvox/action@v1
        with:
          no-lockfile: true
      - run: pnpm test:ember

  try-scenarios:
    name: Compatibility
    runs-on: ubuntu-latest
    needs: [default_tests]
    strategy:
      fail-fast: false
      matrix:
        try-scenario:
        - "ember-3.13"
        - "ember-3.14"
        - "ember-3.16"
        - "ember-3.18"
        - "ember-3.20"
        - "ember-3.24"
        - "ember-3.28"
        - "ember-4.4"
        - "ember-4.8"
        - "ember-4.12"
        - "ember-release"
        - "ember-beta"
        - "ember-canary"
        - "embroider-safe"
        - "embroider-optimized"
    steps:
      - uses: wyvox/action@v1
      - name: Run Tests
        run: >-
          node_modules/.bin/ember try:one ${{ matrix.try-scenario }}
          --skip-cleanup
